tweet_lst = [
  'Terrific reading.',
  'Fascinating look.',
  'That\'s interesting. ',
  'Let me think about that. ',
  'Thanks for your information. ',
  'I\'ll have to ponder that one. ',
  'Wow! ',
  'Hmmmm.. ',
  'That could be. ',
  'Ah-ha~ ',
  'Maybe so.',
  'powerful story. ',
  'we all hope..',
  'Can I say how much I love it.',
  '',
  'Wonderful! ',
  'That\'s one way to look at it. ',
  'appreciate your perspective. ',
  'Cool Tweet. ',
  'Cool! ',
  'Oh oops. ',
  'Even now.',
  'same. ',
  'zzzzzzz...',
  'MUST read. ',
  'marked. ',
  'must-read piece. ',
  'LOVE IT! ',
  'Incredible.',
  'Thanks for doing this! ',
  'Thanks for tweeting this. ',
  'Impressive. ',
  'Well done .',
  'omg. ',
  'OMG~',
  'it\'s true. ',
  'interesting. ',
  'Good thoughts. ',
  'Right.',
  'Nice tweet.',
  'Good post. ',
  'huhhh..',
  'Maybe. ',
  'AGREE.',
  'God bless.',
  'really? ',
  'Amazing. ',
  'Well...',
  'Oops! ',
  'Check it out. ',
  'I don\'t know about this...'
]
